### ISSUE TITLE
Create different package names for versions.

### ISSUE THREAD

**Issue by verbalshadow** [bilgincoskun/brogue-android-port#4]
Creating different package and visible names (Brogue 1.7.5,  Brogue 1.7.5-fixes, Brogue 1.7.4) for versions or fixed versions would allow them to be installed side-by-side. Which I and many others would enjoy.

**Comment by bilgincoskun** [comment]
Given the low download count of vanilla versions and game part of the code will likely be modified for the upcoming zooming implementation, current plan is to drop vanilla versions in an upcoming version. So it is not plausible for me  to maintain them as separate apps. But in long term i want to package them as one apk and let user select it via config file if I can find a way to implement it.

**Comment by verbalshadow** [comment]
Please do not make version selection only config file option. This would defeat the purpose of being able to easily pop into a particular version easily. Maybe a version selection on/before the brogue start-up screen.

**Comment by bilgincoskun** [comment]
Choosing versions  easily certainly makes sense but like I said supporting multiple versions is currently a low-priority goal, so it will take some time to even ship them in the same apk.

**Comment by bilgincoskun** [comment]
Apparently with the building script changing package and app name with environment variable is easier than packaging multiple versions into the one. I still want to do merge them but for now starting with the next release apks with different versions wont override each other.
