### ISSUE TITLE
Screen Resolution is not Set Correctly in Some Devices

### ISSUE THREAD

**Issue by konwulsja** [bilgincoskun/brogue-android-port#5]
Hi!

My first attempt to help in development of anything. 

Attached screenshots best describe the issue, but basically app draws sort of mirrored parts of the game on right margin, where the dock buttons are and in the bottom margin (just a few pixels of it actually).

Best regards!

brogue-175-with-fixes-v0.9

![Screenshot_20191012-121110](https://user-images.githubusercontent.com/17532491/66699771-ce0cef00-ece9-11e9-892a-410407eeb0a5.png)

![Screenshot_20191012-121554](https://user-images.githubusercontent.com/17532491/66699815-1e844c80-ecea-11e9-8056-260510b14f1e.png)

**Comment by bilgincoskun** [comment]
Does it always occur or time to time?

What is your Android device and version?

Also sometimes, some devices tend to report resolution wrong. Can you try to change resolution manually via config file and write if problem still occurs?

**Comment by konwulsja** [comment]
Moto G3 Osprey, Android 7.1.2

Yes, it occurs always. 

I've looked for the config file in: 
/storage/emulated/0/Android/data/org.brogue.brogue/files

But it's not there. 

Could please direct me to it's location?

PS. The game is very much playable as it is anyway.

**Comment by bilgincoskun** [comment]
Currently you need to create and edit it in the location you wrote, It isn't created by default.

**Comment by konwulsja** [comment]
I've created the config file and declared my resolution, which is 1280x720. It did not change anything. 

However after changing it to 1300x720 the game fills the entire screen. 

There's this minor issue at the bottom of the screen (like in the first screenshot), only when I zoom in. It changes the location of the bottom text and buttons (Explore, Menu, etc) as well. Moves them a few pixels to the right. Fully zooming out moves them back and the bottom yellow lines disappear. 

I've tried changing resolution to 1300x725 and 1300x730, but it doesn't help.

**Comment by konwulsja** [comment]
After digging through Reddit (link you provided in my other issue) I can confirm that although custom resolution fills the entire screen, switching back and forth (first come back to game gives blank screen) the rendering is broken.

**Comment by bilgincoskun** [comment]
Suspending/resuming bug and this one are definitely separate issues. This one is definitely caused by screen resolution is not reported correctly.

**Comment by bilgincoskun** [comment]
I've implemented possible fixes in v0.12. If your problem is still not solved feel free to comment so I will re-open the issue.
