### ISSUE TITLE
Tap event is off by about 1 block to the right of actual tap when zoomed in

### ISSUE THREAD

**Issue by blamarche** [bilgincoskun/brogue-android-port#7]
In order to tap accurately I need to tap 1 or more blocks to the left of where I want the click to actually register. This only seems to be the case when zoomed in (seemingly at any amount). When zoomed out fully, the taps seem to activate in the correct location.

I am using a Zenfone 5z which has a fairly odd aspect ratio, not sure if thats related the problem or not. 1080 x 2246 pixels, 18.7:9 ratio

**Comment by bilgincoskun** [comment]
I could not reproduce the bug in my devices but another user also reported the same issue: https://old.reddit.com/r/brogueforum/comments/dnw555/brogue_android_port_v010_release/fj6yyac/
I'll look into it when I have time

**Comment by bilgincoskun** [comment]
I've implemented possible fixes in v0.12. If your problem is still not solved feel free to comment so I will re-open the issue.
